# Cloud Build configuration for building dashboard image
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/medicaid-dashboard:$TAG_NAME'
      - '-t'
      - 'gcr.io/$PROJECT_ID/medicaid-dashboard:latest'
      - '.'
    dir: 'dashboard'
  
  # Push the image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/medicaid-dashboard:$TAG_NAME'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/medicaid-dashboard:latest'

# Store images in GCR
images:
  - 'gcr.io/$PROJECT_ID/medicaid-dashboard:$TAG_NAME'
  - 'gcr.io/$PROJECT_ID/medicaid-dashboard:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
